import type { Auftrag, WorkStepKey, WorkStepState } from "./auftrag-types";

const createDefaultFileState = () => ({
  hatOriginalDatei: false,
  originalDateiName: undefined as string | undefined,
  hatReadyDatei: false,
  readyDateiName: undefined as string | undefined,
});

const createDefaultSteps = (s: boolean, l: boolean, k: boolean, w: boolean, b: boolean, e: boolean) => ({
  scheren: s,
  lasern: l,
  kanten: k,
  schweissen: w,
  behandeln: b,
  eckenGefeilt: e,
});

export const initialAuftraege: Auftrag[] = [
  {
    id: 1,
    commissionNr: "024015",
    projektleiter: "rero",
    projektKurzname: "Geländer Halle 3",
    kundeName: "Muster AG",
    prio: 2,
    projektstatus: "Bearbeitung in TB",
    deadline: "2026-02-20T16:00",
    deadlineBestaetigt: false,
    blechTyp: "S235 5mm",
    format: "3000 x 1500",
    transport: "Kein Transport",
    anzahl: 12,
    flaechM2: 18.5,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, true, true, false, false, true),
  },
  {
    id: 2,
    commissionNr: "024016",
    projektleiter: "niro",
    projektKurzname: "Blechverkleidung Fassade",
    kundeName: "Beispiel GmbH",
    prio: 1,
    projektstatus: "Ready für WS",
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "fassade_ready.pdf",
    deadline: "2026-02-25T08:30",
    deadlineBestaetigt: false,
    blechTyp: "Alu 3mm",
    format: "2500 x 1250",
    transport: "Transport zu Kunde",
    anzahl: 30,
    flaechM2: 42.1,
    ...createDefaultSteps(false, true, true, false, true, false),
  },
  {
    id: 3,
    commissionNr: "024017",
    projektleiter: "alja",
    projektKurzname: "Stahlkonstruktion Dach",
    kundeName: "Bauunternehmung Keller AG",
    prio: 3,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-18T14:00",
    deadlineBestaetigt: true,
    blechTyp: "S355 8mm",
    format: "6000 x 2000",
    transport: "Transport Zwingen-Birsfelden",
    anzahl: 8,
    flaechM2: 96,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, false, true, true, false, true),
    hatReadyDatei: true,
    readyDateiName: "plaene_24017.pdf",
  },
  {
    id: 4,
    commissionNr: "024018",
    projektleiter: "rero",
    projektKurzname: "Abflussrinne Werkstatt",
    kundeName: "Industriebau Müller",
    prio: 2,
    projektstatus: "fertig",
    deadline: "2026-02-12T10:00",
    deadlineBestaetigt: true,
    blechTyp: "Edelstahl 2mm",
    format: "1200 x 800",
    transport: "Kein Transport",
    anzahl: 6,
    flaechM2: 5.76,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, true, true, true, true, true),
  },
  {
    id: 5,
    commissionNr: "024019",
    projektleiter: "tbd",
    projektKurzname: "Schaltschrank-Gehäuse",
    kundeName: "Elektro Schneider",
    prio: 1,
    projektstatus: "Bearbeitung in TB",
    deadline: "2026-03-01T09:00",
    deadlineBestaetigt: false,
    blechTyp: "RAL 7035 1.5mm",
    format: "800 x 600",
    transport: "Transport Birsfelden-Zwingen",
    anzahl: 24,
    flaechM2: 11.52,
    ...createDefaultFileState(),
    ...createDefaultSteps(false, true, true, false, true, true),
  },
  {
    id: 6,
    commissionNr: "024020",
    projektleiter: "niro",
    projektKurzname: "Treppenstufen Außen",
    kundeName: "Hausbau Meier",
    prio: 4,
    projektstatus: "Ready für WS",
    deadline: "2026-02-28T16:00",
    deadlineBestaetigt: false,
    blechTyp: "Alu 4mm",
    format: "1000 x 300",
    transport: "Transport zu Kunde",
    anzahl: 14,
    flaechM2: 4.2,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, true, true, false, true, false),
  },
  {
    id: 7,
    commissionNr: "024021",
    projektleiter: "alja",
    projektKurzname: "Luftkanal HVAC",
    kundeName: "Haustechnik Weber GmbH",
    prio: 2,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-22T12:00",
    deadlineBestaetigt: false,
    blechTyp: "Feuerverzinkt 1mm",
    format: "2000 x 1000",
    transport: "Kein Transport",
    anzahl: 16,
    flaechM2: 32,
    ...createDefaultFileState(),
    hatOriginalDatei: true,
    originalDateiName: "luftkanal_original.dwg",
    ...createDefaultSteps(true, true, true, false, false, true),
  },
  {
    id: 8,
    commissionNr: "024022",
    projektleiter: "rero",
    projektKurzname: "Maschinenabdeckung",
    kundeName: "Werkzeugmaschinen Fischer",
    prio: 1,
    projektstatus: "fertig",
    deadline: "2026-02-08T08:00",
    deadlineBestaetigt: true,
    blechTyp: "S235 3mm",
    format: "1500 x 900",
    transport: "Transport Zwingen-Birsfelden",
    anzahl: 4,
    flaechM2: 5.4,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, false, true, true, false, true),
  },
  {
    id: 9,
    commissionNr: "024023",
    projektleiter: "niro",
    projektKurzname: "Regal-Einlegeböden",
    kundeName: "Lagerlogistik AG",
    prio: 3,
    projektstatus: "Bearbeitung in TB",
    deadline: "2026-02-26T11:00",
    deadlineBestaetigt: false,
    blechTyp: "Rostfrei 2mm",
    format: "1200 x 400",
    transport: "Kein Transport",
    anzahl: 50,
    flaechM2: 24,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, true, true, false, true, true),
  },
  {
    id: 10,
    commissionNr: "024024",
    projektleiter: "alja",
    projektKurzname: "Fassadenelement Nord",
    kundeName: "Architektur Büro Steiner",
    prio: 2,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-24T15:00",
    deadlineBestaetigt: true,
    blechTyp: "Titan-Zink 0.8mm",
    format: "2400 x 1200",
    transport: "Transport zu Kunde",
    anzahl: 12,
    flaechM2: 34.56,
    ...createDefaultFileState(),
    ...createDefaultSteps(false, true, true, false, true, false),
  },
];

export function createStepState(a: Auftrag): Record<WorkStepKey, WorkStepState> {
  const tbErforderlich =
    a.projektstatus === "offen" || a.projektstatus === "Bearbeitung in TB";
  return {
    tb: {
      erforderlich: tbErforderlich,
      isRunning: false,
      totalMinutes: 0,
    },
    scheren: { erforderlich: a.scheren, isRunning: false, totalMinutes: 0 },
    lasern: { erforderlich: a.lasern, isRunning: false, totalMinutes: 0 },
    kanten: { erforderlich: a.kanten, isRunning: false, totalMinutes: 0 },
    schweissen: { erforderlich: a.schweissen, isRunning: false, totalMinutes: 0 },
    behandeln: { erforderlich: a.behandeln, isRunning: false, totalMinutes: 0 },
    eckenGefeilt: {
      erforderlich: a.eckenGefeilt,
      isRunning: false,
      totalMinutes: 0,
    },
  };
}
