import type { Auftrag, WorkStepKey, WorkStepState } from "./auftrag-types";

const FERTIGUNG_STEP_KEYS: WorkStepKey[] = [
  "scheren",
  "lasern",
  "kanten",
  "schweissen",
  "behandeln",
  "eckenGefeilt",
];

/** Fertigungsschritt (nicht TB) – benötigt Lead für Start/Pause/Stop */
export function isFertigungsschritt(key: WorkStepKey): boolean {
  return FERTIGUNG_STEP_KEYS.includes(key);
}

/** Ready für Transport nur wenn alle Fertigungsschritte gestoppt sind und Lead ausgefüllt */
export function canSetReadyFürTransport(a: Auftrag): boolean {
  const steps = a.steps ?? createStepState(a);
  for (const key of FERTIGUNG_STEP_KEYS) {
    const step = steps[key];
    if (!step?.erforderlich) continue;
    if (step.isRunning || step.isPaused) return false;
    if (!step.lead?.trim()) return false;
  }
  return true;
}

/** Transport geplant nur wenn vorher Ready für Transport */
export function canSetTransportGeplant(a: Auftrag): boolean {
  return a.projektstatus === "Ready für Transport";
}

/** Fertig nur wenn vorher Transport geplant */
export function canSetFertig(a: Auftrag): boolean {
  return a.projektstatus === "Transport geplant";
}

const createDefaultFileState = () => ({
  hatOriginalDatei: false,
  originalDateiName: undefined as string | undefined,
  hatReadyDatei: false,
  readyDateiName: undefined as string | undefined,
});

const createDefaultSteps = (s: boolean, l: boolean, k: boolean, w: boolean, b: boolean, e: boolean) => ({
  scheren: s,
  lasern: l,
  kanten: k,
  schweissen: w,
  behandeln: b,
  eckenGefeilt: e,
});

export const initialAuftraege: Auftrag[] = [
  {
    id: 1,
    commissionNr: "024015",
    projektleiter: "rero",
    projektKurzname: "Geländer Halle 3",
    kundeName: "Muster AG",
    prio: 2,
    projektstatus: "Bearbeitung in TB",
    deadline: "2026-02-20T16:00",
    deadlineBestaetigt: false,
    blechTyp: "S235 5mm",
    format: "3000 x 1500",
    transport: "Kein Transport",
    anzahl: 12,
    flaechM2: 18.5,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, true, true, false, false, true),
  },
  {
    id: 2,
    commissionNr: "024016",
    projektleiter: "niro",
    projektKurzname: "Blechverkleidung Fassade",
    kundeName: "Beispiel GmbH",
    prio: 1,
    projektstatus: "Ready für WS",
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "fassade_ready.pdf",
    deadline: "2026-02-25T08:30",
    deadlineBestaetigt: false,
    blechTyp: "Alu 3mm",
    format: "2500 x 1250",
    transport: "Transport zu Kunde",
    anzahl: 30,
    flaechM2: 42.1,
    ...createDefaultSteps(false, true, true, false, true, false),
  },
  {
    id: 3,
    commissionNr: "024017",
    projektleiter: "alja",
    projektKurzname: "Stahlkonstruktion Dach",
    kundeName: "Bauunternehmung Keller AG",
    prio: 3,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-18T14:00",
    deadlineBestaetigt: true,
    blechTyp: "S355 8mm",
    format: "6000 x 2000",
    transport: "Transport Zwingen-Birsfelden",
    anzahl: 8,
    flaechM2: 96,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, false, true, true, false, true),
    hatReadyDatei: true,
    readyDateiName: "plaene_24017.pdf",
  },
  {
    id: 4,
    commissionNr: "024018",
    projektleiter: "rero",
    projektKurzname: "Abflussrinne Werkstatt",
    kundeName: "Industriebau Müller",
    prio: 2,
    projektstatus: "fertig",
    fertigAm: "2026-02-12T09:45:00.000Z",
    deadline: "2026-02-12T10:00",
    deadlineBestaetigt: true,
    blechTyp: "Edelstahl 2mm",
    format: "1200 x 800",
    transport: "Kein Transport",
    anzahl: 6,
    flaechM2: 5.76,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, true, true, true, true, true),
  },
  {
    id: 5,
    commissionNr: "024019",
    projektleiter: "tbd",
    projektKurzname: "Schaltschrank-Gehäuse",
    kundeName: "Elektro Schneider",
    prio: 1,
    projektstatus: "Bearbeitung in TB",
    deadline: "2026-03-01T09:00",
    deadlineBestaetigt: false,
    blechTyp: "RAL 7035 1.5mm",
    format: "800 x 600",
    transport: "Transport Birsfelden-Zwingen",
    anzahl: 24,
    flaechM2: 11.52,
    ...createDefaultFileState(),
    ...createDefaultSteps(false, true, true, false, true, true),
  },
  {
    id: 6,
    commissionNr: "024020",
    projektleiter: "niro",
    projektKurzname: "Treppenstufen Außen",
    kundeName: "Hausbau Meier",
    prio: 4,
    projektstatus: "Ready für WS",
    deadline: "2026-02-28T16:00",
    deadlineBestaetigt: false,
    blechTyp: "Alu 4mm",
    format: "1000 x 300",
    transport: "Transport zu Kunde",
    anzahl: 14,
    flaechM2: 4.2,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, true, true, false, true, false),
  },
  {
    id: 7,
    commissionNr: "024021",
    projektleiter: "alja",
    projektKurzname: "Luftkanal HVAC",
    kundeName: "Haustechnik Weber GmbH",
    prio: 2,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-22T12:00",
    deadlineBestaetigt: false,
    blechTyp: "Feuerverzinkt 1mm",
    format: "2000 x 1000",
    transport: "Kein Transport",
    anzahl: 16,
    flaechM2: 32,
    ...createDefaultFileState(),
    hatOriginalDatei: true,
    originalDateiName: "luftkanal_original.dwg",
    ...createDefaultSteps(true, true, true, false, false, true),
  },
  {
    id: 8,
    commissionNr: "024022",
    projektleiter: "rero",
    projektKurzname: "Maschinenabdeckung",
    kundeName: "Werkzeugmaschinen Fischer",
    prio: 1,
    projektstatus: "fertig",
    fertigAm: "2026-02-08T07:52:00.000Z",
    deadline: "2026-02-08T08:00",
    deadlineBestaetigt: true,
    blechTyp: "S235 3mm",
    format: "1500 x 900",
    transport: "Transport Zwingen-Birsfelden",
    anzahl: 4,
    flaechM2: 5.4,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, false, true, true, false, true),
  },
  {
    id: 9,
    commissionNr: "024023",
    projektleiter: "niro",
    projektKurzname: "Regal-Einlegeböden",
    kundeName: "Lagerlogistik AG",
    prio: 3,
    projektstatus: "Bearbeitung in TB",
    deadline: "2026-02-26T11:00",
    deadlineBestaetigt: false,
    blechTyp: "Rostfrei 2mm",
    format: "1200 x 400",
    transport: "Kein Transport",
    anzahl: 50,
    flaechM2: 24,
    ...createDefaultFileState(),
    ...createDefaultSteps(true, true, true, false, true, true),
  },
  {
    id: 10,
    commissionNr: "024024",
    projektleiter: "alja",
    projektKurzname: "Fassadenelement Nord",
    kundeName: "Architektur Büro Steiner",
    prio: 2,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-24T15:00",
    deadlineBestaetigt: true,
    blechTyp: "Titan-Zink 0.8mm",
    format: "2400 x 1200",
    transport: "Transport zu Kunde",
    anzahl: 12,
    flaechM2: 34.56,
    ...createDefaultFileState(),
    ...createDefaultSteps(false, true, true, false, true, false),
  },
  // 5 Demo-Projekte in Bearbeitung WS mit verschiedenen Fertigungsschritt-Zuständen
  {
    id: 11,
    commissionNr: "024025",
    projektleiter: "rero",
    projektKurzname: "Werkbank-Untergestell",
    kundeName: "Schreinerei Holzmann",
    prio: 1,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-21T16:00",
    deadlineBestaetigt: false,
    blechTyp: "S235 4mm",
    format: "2000 x 1000",
    transport: "Kein Transport",
    anzahl: 6,
    flaechM2: 20,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "werkbank_ready.pdf",
    ...createDefaultSteps(true, true, true, false, false, false),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 15,
        lead: "mifi",
        startedBy: "mifi",
        stoppedBy: "mifi",
      },
      lasern: {
        erforderlich: true,
        isRunning: true,
        isPaused: false,
        totalMinutes: 8,
        lead: "kaku",
        startedBy: "kaku",
        startedAt: Date.now() - 8 * 60 * 1000,
      },
      kanten: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 0,
        lead: "saro",
      },
      schweissen: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      behandeln: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      eckenGefeilt: { erforderlich: false, isRunning: false, totalMinutes: 0 },
    },
  },
  {
    id: 12,
    commissionNr: "024026",
    projektleiter: "niro",
    projektKurzname: "Schutzblech Maschine",
    kundeName: "Industrie Anlagen AG",
    prio: 2,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-23T10:00",
    deadlineBestaetigt: true,
    blechTyp: "Alu 3mm",
    format: "1500 x 800",
    transport: "Transport Zwingen-Birsfelden",
    anzahl: 4,
    flaechM2: 9.6,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "schutzblech.pdf",
    ...createDefaultSteps(true, true, true, true, false, false),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 22,
        lead: "hema",
        startedBy: "hema",
        stoppedBy: "hema",
      },
      lasern: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 18,
        lead: "kaku",
        startedBy: "kaku",
        stoppedBy: "kaku",
      },
      kanten: {
        erforderlich: true,
        isRunning: false,
        isPaused: true,
        totalMinutes: 12,
        lead: "saro",
        startedBy: "saro",
        pausedBy: "saro",
      },
      schweissen: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 5,
        lead: "alex",
        startedBy: "alex",
        stoppedBy: "alex",
      },
      behandeln: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      eckenGefeilt: { erforderlich: false, isRunning: false, totalMinutes: 0 },
    },
  },
  {
    id: 13,
    commissionNr: "024027",
    projektleiter: "alja",
    projektKurzname: "Dachrinne Industriehalle",
    kundeName: "Metallbau Schmidt",
    prio: 3,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-26T14:00",
    deadlineBestaetigt: false,
    blechTyp: "Feuerverzinkt 1.5mm",
    format: "3000 x 1000",
    transport: "Kein Transport",
    anzahl: 20,
    flaechM2: 60,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "dachrinne_ready.pdf",
    ...createDefaultSteps(true, true, true, false, true, false),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: {
        erforderlich: true,
        isRunning: true,
        isPaused: false,
        totalMinutes: 35,
        lead: "mifi",
        startedBy: "mifi",
        startedAt: Date.now() - 12 * 60 * 1000,
      },
      lasern: {
        erforderlich: true,
        isRunning: false,
        isPaused: true,
        totalMinutes: 28,
        lead: "kaku",
        startedBy: "kaku",
        pausedBy: "kaku",
      },
      kanten: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 42,
        lead: "saro",
        startedBy: "saro",
        stoppedBy: "saro",
      },
      schweissen: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      behandeln: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 0,
        lead: "hema",
      },
      eckenGefeilt: { erforderlich: false, isRunning: false, totalMinutes: 0 },
    },
  },
  {
    id: 14,
    commissionNr: "024028",
    projektleiter: "rero",
    projektKurzname: "Kabelkanal-Deckel",
    kundeName: "Elektroinstallation Müller",
    prio: 1,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-20T11:00",
    deadlineBestaetigt: true,
    blechTyp: "RAL 7035 1mm",
    format: "600 x 400",
    transport: "Transport Birsfelden-Zwingen",
    anzahl: 40,
    flaechM2: 9.6,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "kabelkanal.pdf",
    ...createDefaultSteps(false, true, true, false, true, false),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      lasern: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 45,
        lead: "kaku",
        startedBy: "kaku",
        stoppedBy: "kaku",
      },
      kanten: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 32,
        lead: "saro",
        startedBy: "saro",
        stoppedBy: "saro",
      },
      schweissen: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      behandeln: {
        erforderlich: true,
        isRunning: true,
        isPaused: false,
        totalMinutes: 18,
        lead: "hema",
        startedBy: "hema",
        startedAt: Date.now() - 18 * 60 * 1000,
      },
      eckenGefeilt: { erforderlich: false, isRunning: false, totalMinutes: 0 },
    },
  },
  {
    id: 15,
    commissionNr: "024029",
    projektleiter: "niro",
    projektKurzname: "Montagehilfe Vorrichtung",
    kundeName: "Fertigungstechnik AG",
    prio: 2,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-25T09:00",
    deadlineBestaetigt: false,
    blechTyp: "S235 6mm",
    format: "1200 x 600",
    transport: "Kein Transport",
    anzahl: 2,
    flaechM2: 1.44,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "vorrichtung_ready.pdf",
    ...createDefaultSteps(true, true, true, true, true, true),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 25,
        lead: "mifi",
        startedBy: "mifi",
        stoppedBy: "mifi",
      },
      lasern: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 38,
        lead: "kaku",
        startedBy: "kaku",
        stoppedBy: "kaku",
      },
      kanten: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 55,
        lead: "saro",
        startedBy: "saro",
        stoppedBy: "saro",
      },
      schweissen: {
        erforderlich: true,
        isRunning: false,
        isPaused: true,
        totalMinutes: 20,
        lead: "alex",
        startedBy: "alex",
        pausedBy: "alex",
      },
      behandeln: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 12,
        lead: "hema",
        startedBy: "hema",
        stoppedBy: "hema",
      },
      eckenGefeilt: {
        erforderlich: true,
        isRunning: true,
        isPaused: false,
        totalMinutes: 5,
        lead: "mifi",
        startedBy: "mifi",
        startedAt: Date.now() - 5 * 60 * 1000,
      },
    },
  },
  // Demo-Projekte Ready für Transport
  {
    id: 16,
    commissionNr: "024030",
    projektleiter: "rero",
    projektKurzname: "Stahlträger Verstärkung",
    kundeName: "Hochbau Müller AG",
    prio: 1,
    projektstatus: "Ready für Transport",
    deadline: "2026-02-27T14:00",
    deadlineBestaetigt: true,
    blechTyp: "S355 10mm",
    format: "4000 x 1500",
    transport: "Transport zu Kunde",
    anzahl: 4,
    flaechM2: 60,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "stahtraeger_ready.pdf",
    ...createDefaultSteps(true, true, true, true, false, true),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 45,
        lead: "mifi",
        startedBy: "mifi",
        stoppedBy: "mifi",
      },
      lasern: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 62,
        lead: "kaku",
        startedBy: "kaku",
        stoppedBy: "kaku",
      },
      kanten: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 38,
        lead: "saro",
        startedBy: "saro",
        stoppedBy: "saro",
      },
      schweissen: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 95,
        lead: "alex",
        startedBy: "alex",
        stoppedBy: "alex",
      },
      behandeln: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      eckenGefeilt: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 22,
        lead: "hema",
        startedBy: "hema",
        stoppedBy: "hema",
      },
    },
  },
  {
    id: 17,
    commissionNr: "024031",
    projektleiter: "niro",
    projektKurzname: "Lüftungsgitter Außen",
    kundeName: "Gebäudetechnik Weber",
    prio: 2,
    projektstatus: "Ready für Transport",
    deadline: "2026-02-28T10:00",
    deadlineBestaetigt: false,
    blechTyp: "Feuerverzinkt 1.5mm",
    format: "800 x 600",
    transport: "Transport Zwingen-Birsfelden",
    anzahl: 8,
    flaechM2: 3.84,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "lueftungsgitter.pdf",
    ...createDefaultSteps(true, true, true, false, true, false),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 18,
        lead: "mifi",
        startedBy: "mifi",
        stoppedBy: "mifi",
      },
      lasern: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 28,
        lead: "kaku",
        startedBy: "kaku",
        stoppedBy: "kaku",
      },
      kanten: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 15,
        lead: "saro",
        startedBy: "saro",
        stoppedBy: "saro",
      },
      schweissen: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      behandeln: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 12,
        lead: "hema",
        startedBy: "hema",
        stoppedBy: "hema",
      },
      eckenGefeilt: { erforderlich: false, isRunning: false, totalMinutes: 0 },
    },
  },
  // Demo-Projekte Transport geplant
  {
    id: 18,
    commissionNr: "024032",
    projektleiter: "alja",
    projektKurzname: "Fassadenelement Süd",
    kundeName: "Architektur Büro Steiner",
    prio: 1,
    projektstatus: "Transport geplant",
    deadline: "2026-03-01T09:00",
    deadlineBestaetigt: true,
    blechTyp: "Titan-Zink 0.8mm",
    format: "2400 x 1200",
    transport: "Transport zu Kunde",
    anzahl: 16,
    flaechM2: 46.08,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "fassade_sued_ready.pdf",
    ...createDefaultSteps(false, true, true, false, true, false),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      lasern: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 72,
        lead: "kaku",
        startedBy: "kaku",
        stoppedBy: "kaku",
      },
      kanten: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 48,
        lead: "saro",
        startedBy: "saro",
        stoppedBy: "saro",
      },
      schweissen: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      behandeln: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 35,
        lead: "hema",
        startedBy: "hema",
        stoppedBy: "hema",
      },
      eckenGefeilt: { erforderlich: false, isRunning: false, totalMinutes: 0 },
    },
  },
  {
    id: 19,
    commissionNr: "024033",
    projektleiter: "rero",
    projektKurzname: "Blechkabinen-Wand",
    kundeName: "Industriebau Keller",
    prio: 2,
    projektstatus: "Transport geplant",
    deadline: "2026-02-26T16:00",
    deadlineBestaetigt: true,
    blechTyp: "S235 3mm",
    format: "2000 x 1000",
    transport: "Transport Birsfelden-Zwingen",
    anzahl: 12,
    flaechM2: 24,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "kabinen_wand.pdf",
    ...createDefaultSteps(true, true, true, true, false, true),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 32,
        lead: "mifi",
        startedBy: "mifi",
        stoppedBy: "mifi",
      },
      lasern: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 55,
        lead: "kaku",
        startedBy: "kaku",
        stoppedBy: "kaku",
      },
      kanten: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 42,
        lead: "saro",
        startedBy: "saro",
        stoppedBy: "saro",
      },
      schweissen: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 68,
        lead: "alex",
        startedBy: "alex",
        stoppedBy: "alex",
      },
      behandeln: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      eckenGefeilt: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 18,
        lead: "hema",
        startedBy: "hema",
        stoppedBy: "hema",
      },
    },
  },
  // Commission 024034 – 3 Projekte (Ready für WS / Bearbeitung in WS)
  {
    id: 20,
    commissionNr: "024034-1",
    projektleiter: "niro",
    projektKurzname: "Treppenhaus Geländer EG",
    kundeName: "Mehrfamilienhaus AG",
    prio: 1,
    projektstatus: "Ready für WS",
    deadline: "2026-02-22T10:00",
    deadlineBestaetigt: true,
    blechTyp: "S235 4mm",
    format: "1500 x 800",
    transport: "Kein Transport",
    anzahl: 4,
    flaechM2: 9.6,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "geländer_eg.pdf",
    ...createDefaultSteps(true, true, true, false, true, false),
  },
  {
    id: 21,
    commissionNr: "024034-2",
    projektleiter: "niro",
    projektKurzname: "Treppenhaus Geländer 1. OG",
    kundeName: "Mehrfamilienhaus AG",
    prio: 2,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-22T10:00",
    deadlineBestaetigt: true,
    blechTyp: "S235 4mm",
    format: "1500 x 800",
    transport: "Kein Transport",
    anzahl: 4,
    flaechM2: 9.6,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "geländer_1og.pdf",
    ...createDefaultSteps(true, true, true, false, true, false),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 12,
        lead: "mifi",
        startedBy: "mifi",
        stoppedBy: "mifi",
      },
      lasern: {
        erforderlich: true,
        isRunning: true,
        isPaused: false,
        totalMinutes: 5,
        lead: "kaku",
        startedBy: "kaku",
        startedAt: Date.now() - 5 * 60 * 1000,
      },
      kanten: { erforderlich: true, isRunning: false, totalMinutes: 0, lead: "saro" },
      schweissen: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      behandeln: { erforderlich: true, isRunning: false, totalMinutes: 0, lead: "hema" },
      eckenGefeilt: { erforderlich: false, isRunning: false, totalMinutes: 0 },
    },
  },
  {
    id: 22,
    commissionNr: "024034-3",
    projektleiter: "niro",
    projektKurzname: "Treppenhaus Geländer 2. OG",
    kundeName: "Mehrfamilienhaus AG",
    prio: 3,
    projektstatus: "Ready für WS",
    deadline: "2026-02-22T10:00",
    deadlineBestaetigt: true,
    blechTyp: "S235 4mm",
    format: "1500 x 800",
    transport: "Kein Transport",
    anzahl: 4,
    flaechM2: 9.6,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "geländer_2og.pdf",
    ...createDefaultSteps(true, true, true, false, true, false),
  },
  // Commission 024035 – 2 Projekte (Offen / Bearbeitung in TB)
  {
    id: 23,
    commissionNr: "024035-1",
    projektleiter: "alja",
    projektKurzname: "Schaltschrank Reihe A",
    kundeName: "Elektroinstallation Müller",
    prio: 1,
    projektstatus: "Bearbeitung in TB",
    deadline: "2026-03-05T14:00",
    deadlineBestaetigt: false,
    blechTyp: "RAL 7035 1.5mm",
    format: "800 x 600",
    transport: "Transport Birsfelden-Zwingen",
    anzahl: 6,
    flaechM2: 2.88,
    ...createDefaultFileState(),
    ...createDefaultSteps(false, true, true, false, true, true),
  },
  {
    id: 24,
    commissionNr: "024035-2",
    projektleiter: "alja",
    projektKurzname: "Schaltschrank Reihe B",
    kundeName: "Elektroinstallation Müller",
    prio: 2,
    projektstatus: "offen",
    deadline: "2026-03-05T14:00",
    deadlineBestaetigt: false,
    blechTyp: "RAL 7035 1.5mm",
    format: "800 x 600",
    transport: "Transport Birsfelden-Zwingen",
    anzahl: 6,
    flaechM2: 2.88,
    ...createDefaultFileState(),
    ...createDefaultSteps(false, true, true, false, true, true),
  },
  // Commission 024036 – 4 Projekte (verschiedene Stati)
  {
    id: 25,
    commissionNr: "024036-1",
    projektleiter: "rero",
    projektKurzname: "Fassade Ost Segment 1",
    kundeName: "Bürogebäude Zentrum AG",
    prio: 1,
    projektstatus: "fertig",
    fertigAm: "2026-02-15T15:38:00.000Z",
    deadline: "2026-02-15T16:00",
    deadlineBestaetigt: true,
    blechTyp: "Alu 3mm",
    format: "3000 x 1200",
    transport: "Transport zu Kunde",
    anzahl: 8,
    flaechM2: 28.8,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "fassade_ost_1.pdf",
    ...createDefaultSteps(true, true, true, false, true, false),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: { erforderlich: true, isRunning: false, totalMinutes: 35, lead: "mifi", startedBy: "mifi", stoppedBy: "mifi" },
      lasern: { erforderlich: true, isRunning: false, totalMinutes: 48, lead: "kaku", startedBy: "kaku", stoppedBy: "kaku" },
      kanten: { erforderlich: true, isRunning: false, totalMinutes: 42, lead: "saro", startedBy: "saro", stoppedBy: "saro" },
      schweissen: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      behandeln: { erforderlich: true, isRunning: false, totalMinutes: 28, lead: "hema", startedBy: "hema", stoppedBy: "hema" },
      eckenGefeilt: { erforderlich: false, isRunning: false, totalMinutes: 0 },
    },
  },
  {
    id: 26,
    commissionNr: "024036-2",
    projektleiter: "rero",
    projektKurzname: "Fassade Ost Segment 2",
    kundeName: "Bürogebäude Zentrum AG",
    prio: 2,
    projektstatus: "Transport geplant",
    deadline: "2026-02-20T16:00",
    deadlineBestaetigt: true,
    blechTyp: "Alu 3mm",
    format: "3000 x 1200",
    transport: "Transport zu Kunde",
    anzahl: 8,
    flaechM2: 28.8,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "fassade_ost_2.pdf",
    ...createDefaultSteps(true, true, true, false, true, false),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: { erforderlich: true, isRunning: false, totalMinutes: 38, lead: "mifi", startedBy: "mifi", stoppedBy: "mifi" },
      lasern: { erforderlich: true, isRunning: false, totalMinutes: 52, lead: "kaku", startedBy: "kaku", stoppedBy: "kaku" },
      kanten: { erforderlich: true, isRunning: false, totalMinutes: 45, lead: "saro", startedBy: "saro", stoppedBy: "saro" },
      schweissen: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      behandeln: { erforderlich: true, isRunning: false, totalMinutes: 30, lead: "hema", startedBy: "hema", stoppedBy: "hema" },
      eckenGefeilt: { erforderlich: false, isRunning: false, totalMinutes: 0 },
    },
  },
  {
    id: 27,
    commissionNr: "024036-3",
    projektleiter: "rero",
    projektKurzname: "Fassade Ost Segment 3",
    kundeName: "Bürogebäude Zentrum AG",
    prio: 3,
    projektstatus: "Ready für Transport",
    deadline: "2026-02-25T16:00",
    deadlineBestaetigt: true,
    blechTyp: "Alu 3mm",
    format: "3000 x 1200",
    transport: "Transport zu Kunde",
    anzahl: 8,
    flaechM2: 28.8,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "fassade_ost_3.pdf",
    ...createDefaultSteps(true, true, true, false, true, false),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: { erforderlich: true, isRunning: false, totalMinutes: 32, lead: "mifi", startedBy: "mifi", stoppedBy: "mifi" },
      lasern: { erforderlich: true, isRunning: false, totalMinutes: 45, lead: "kaku", startedBy: "kaku", stoppedBy: "kaku" },
      kanten: { erforderlich: true, isRunning: false, totalMinutes: 40, lead: "saro", startedBy: "saro", stoppedBy: "saro" },
      schweissen: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      behandeln: { erforderlich: true, isRunning: false, totalMinutes: 25, lead: "hema", startedBy: "hema", stoppedBy: "hema" },
      eckenGefeilt: { erforderlich: false, isRunning: false, totalMinutes: 0 },
    },
  },
  {
    id: 28,
    commissionNr: "024036-4",
    projektleiter: "rero",
    projektKurzname: "Fassade Ost Segment 4",
    kundeName: "Bürogebäude Zentrum AG",
    prio: 4,
    projektstatus: "Bearbeitung in WS",
    deadline: "2026-02-28T16:00",
    deadlineBestaetigt: false,
    blechTyp: "Alu 3mm",
    format: "3000 x 1200",
    transport: "Transport zu Kunde",
    anzahl: 8,
    flaechM2: 28.8,
    ...createDefaultFileState(),
    hatReadyDatei: true,
    readyDateiName: "fassade_ost_4.pdf",
    ...createDefaultSteps(true, true, true, false, true, false),
    steps: {
      tb: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      scheren: {
        erforderlich: true,
        isRunning: false,
        isPaused: false,
        totalMinutes: 28,
        lead: "mifi",
        startedBy: "mifi",
        stoppedBy: "mifi",
      },
      lasern: {
        erforderlich: true,
        isRunning: true,
        isPaused: false,
        totalMinutes: 15,
        lead: "kaku",
        startedBy: "kaku",
        startedAt: Date.now() - 15 * 60 * 1000,
      },
      kanten: { erforderlich: true, isRunning: false, totalMinutes: 0, lead: "saro" },
      schweissen: { erforderlich: false, isRunning: false, totalMinutes: 0 },
      behandeln: { erforderlich: true, isRunning: false, totalMinutes: 0, lead: "hema" },
      eckenGefeilt: { erforderlich: false, isRunning: false, totalMinutes: 0 },
    },
  },
];

export function createStepState(a: Auftrag): Record<WorkStepKey, WorkStepState> {
  const tbErforderlich =
    a.projektstatus === "offen" || a.projektstatus === "Bearbeitung in TB";
  return {
    tb: {
      erforderlich: tbErforderlich,
      isRunning: false,
      totalMinutes: 0,
    },
    scheren: { erforderlich: a.scheren, isRunning: false, totalMinutes: 0 },
    lasern: { erforderlich: a.lasern, isRunning: false, totalMinutes: 0 },
    kanten: { erforderlich: a.kanten, isRunning: false, totalMinutes: 0 },
    schweissen: { erforderlich: a.schweissen, isRunning: false, totalMinutes: 0 },
    behandeln: { erforderlich: a.behandeln, isRunning: false, totalMinutes: 0 },
    eckenGefeilt: {
      erforderlich: a.eckenGefeilt,
      isRunning: false,
      totalMinutes: 0,
    },
  };
}
